// 50+ curated sources for the Radar system
// Edit freely — this is the seed config loaded on first run.

import type { SourceConfig } from './types';

export const SEED_SOURCES: SourceConfig[] = [
  // ── AI ─────────────────────────────────────────────────────────────────────
  {
    name: 'The Verge – AI',
    category: 'AI',
    type: 'rss',
    homepageUrl: 'https://www.theverge.com/ai-artificial-intelligence',
    feedUrl: 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml',
    enabled: true,
    trustScore: 8,
    speedScore: 9,
    noiseScore: 5,
    notes: 'Good early coverage of AI products and announcements',
  },
  {
    name: 'VentureBeat AI',
    category: 'AI',
    type: 'rss',
    homepageUrl: 'https://venturebeat.com/category/ai/',
    feedUrl: 'https://venturebeat.com/category/ai/feed/',
    enabled: true,
    trustScore: 7,
    speedScore: 8,
    noiseScore: 6,
    notes: 'Enterprise AI focus, decent signal',
  },
  {
    name: 'MIT Technology Review – AI',
    category: 'AI',
    type: 'rss',
    homepageUrl: 'https://www.technologyreview.com/topic/artificial-intelligence/',
    feedUrl: 'https://www.technologyreview.com/feed/',
    enabled: true,
    trustScore: 9,
    speedScore: 6,
    noiseScore: 3,
    notes: 'Deep, reliable — slightly slower to publish',
  },
  {
    name: 'Ars Technica – AI',
    category: 'AI',
    type: 'rss',
    homepageUrl: 'https://arstechnica.com/ai/',
    feedUrl: 'https://feeds.arstechnica.com/arstechnica/index',
    enabled: true,
    trustScore: 8,
    speedScore: 7,
    noiseScore: 5,
  },
  {
    name: 'AI Weirdness (Janelle Shane)',
    category: 'AI',
    type: 'rss',
    homepageUrl: 'https://www.aiweirdness.com',
    feedUrl: 'https://www.aiweirdness.com/rss/',
    enabled: true,
    trustScore: 7,
    speedScore: 4,
    noiseScore: 2,
    notes: 'Niche AI experiments, low volume, high signal',
  },
  {
    name: 'Interconnects (Nathan Lambert)',
    category: 'AI',
    type: 'rss',
    homepageUrl: 'https://www.interconnects.ai',
    feedUrl: 'https://www.interconnects.ai/feed',
    enabled: true,
    trustScore: 9,
    speedScore: 5,
    noiseScore: 2,
    notes: 'Deep ML takes, insider knowledge',
  },
  {
    name: 'Import AI (Jack Clark)',
    category: 'AI',
    type: 'rss',
    homepageUrl: 'https://importai.substack.com',
    feedUrl: 'https://importai.substack.com/feed',
    enabled: true,
    trustScore: 9,
    speedScore: 4,
    noiseScore: 1,
    notes: 'Weekly, very high signal for AI research',
  },

  // ── Search ─────────────────────────────────────────────────────────────────
  {
    name: 'Search Engine Land',
    category: 'Search',
    type: 'rss',
    homepageUrl: 'https://searchengineland.com',
    feedUrl: 'https://searchengineland.com/feed',
    enabled: true,
    trustScore: 9,
    speedScore: 9,
    noiseScore: 5,
    notes: 'Best for Google/Bing news, fast',
  },
  {
    name: 'Search Engine Journal',
    category: 'Search',
    type: 'rss',
    homepageUrl: 'https://www.searchenginejournal.com',
    feedUrl: 'https://www.searchenginejournal.com/feed/',
    enabled: true,
    trustScore: 8,
    speedScore: 8,
    noiseScore: 5,
  },
  {
    name: 'Search Engine Roundtable',
    category: 'Search',
    type: 'rss',
    homepageUrl: 'https://www.seroundtable.com',
    feedUrl: 'https://www.seroundtable.com/index.xml',
    enabled: true,
    trustScore: 8,
    speedScore: 10,
    noiseScore: 6,
    notes: 'Barry Schwartz – fastest Google news anywhere',
  },
  {
    name: 'Google Search Central Blog',
    category: 'Search',
    type: 'rss',
    homepageUrl: 'https://developers.google.com/search/blog',
    feedUrl: 'https://developers.google.com/search/blog/atom.xml',
    enabled: true,
    trustScore: 10,
    speedScore: 8,
    noiseScore: 2,
    notes: 'Official Google — low volume, maximum authority',
  },
  {
    name: 'Bing Webmaster Blog',
    category: 'Search',
    type: 'rss',
    homepageUrl: 'https://blogs.bing.com/webmaster',
    feedUrl: 'https://blogs.bing.com/webmaster/rss.aspx',
    enabled: true,
    trustScore: 9,
    speedScore: 7,
    noiseScore: 2,
  },

  // ── SEO ────────────────────────────────────────────────────────────────────
  {
    name: 'Ahrefs Blog',
    category: 'SEO',
    type: 'rss',
    homepageUrl: 'https://ahrefs.com/blog',
    feedUrl: 'https://ahrefs.com/blog/feed/',
    enabled: true,
    trustScore: 9,
    speedScore: 5,
    noiseScore: 2,
    notes: 'High quality, deep SEO research',
  },
  {
    name: 'Moz Blog',
    category: 'SEO',
    type: 'rss',
    homepageUrl: 'https://moz.com/blog',
    feedUrl: 'https://moz.com/blog/feed',
    enabled: true,
    trustScore: 8,
    speedScore: 5,
    noiseScore: 3,
  },
  {
    name: 'Semrush Blog',
    category: 'SEO',
    type: 'rss',
    homepageUrl: 'https://www.semrush.com/blog',
    feedUrl: 'https://www.semrush.com/blog/feed/',
    enabled: true,
    trustScore: 7,
    speedScore: 5,
    noiseScore: 4,
  },
  {
    name: 'Marie Haynes Consulting',
    category: 'SEO',
    type: 'rss',
    homepageUrl: 'https://www.mariehaynes.com',
    feedUrl: 'https://www.mariehaynes.com/feed/',
    enabled: true,
    trustScore: 9,
    speedScore: 5,
    noiseScore: 1,
    notes: 'Google algorithm expert, very high signal',
  },
  {
    name: 'Lily Ray SEO',
    category: 'SEO',
    type: 'rss',
    homepageUrl: 'https://www.lilyray.nyc',
    feedUrl: 'https://www.lilyray.nyc/feed/',
    enabled: true,
    trustScore: 8,
    speedScore: 4,
    noiseScore: 1,
  },

  // ── Social ─────────────────────────────────────────────────────────────────
  {
    name: 'Social Media Today',
    category: 'Social',
    type: 'rss',
    homepageUrl: 'https://www.socialmediatoday.com',
    feedUrl: 'https://www.socialmediatoday.com/feed/',
    enabled: true,
    trustScore: 7,
    speedScore: 8,
    noiseScore: 6,
  },
  {
    name: 'Social Media Examiner',
    category: 'Social',
    type: 'rss',
    homepageUrl: 'https://www.socialmediaexaminer.com',
    feedUrl: 'https://www.socialmediaexaminer.com/feed/',
    enabled: true,
    trustScore: 7,
    speedScore: 6,
    noiseScore: 4,
  },
  {
    name: 'Later Blog',
    category: 'Social',
    type: 'rss',
    homepageUrl: 'https://later.com/blog',
    feedUrl: 'https://later.com/blog/feed/',
    enabled: true,
    trustScore: 6,
    speedScore: 5,
    noiseScore: 4,
    notes: 'Social scheduling/platform changes',
  },
  {
    name: 'Twitter/X Engineering Blog',
    category: 'Social',
    type: 'rss',
    homepageUrl: 'https://blog.twitter.com/engineering',
    feedUrl: 'https://blog.twitter.com/engineering/en_us/blog.rss',
    enabled: true,
    trustScore: 9,
    speedScore: 5,
    noiseScore: 2,
    notes: 'Official X engineering — low volume, high authority',
  },

  // ── WordPress ──────────────────────────────────────────────────────────────
  {
    name: 'WordPress.org News',
    category: 'WordPress',
    type: 'rss',
    homepageUrl: 'https://wordpress.org/news',
    feedUrl: 'https://wordpress.org/news/feed/',
    enabled: true,
    trustScore: 10,
    speedScore: 7,
    noiseScore: 1,
    notes: 'Official WordPress releases and announcements',
  },
  {
    name: 'WP Tavern',
    category: 'WordPress',
    type: 'rss',
    homepageUrl: 'https://wptavern.com',
    feedUrl: 'https://wptavern.com/feed',
    enabled: true,
    trustScore: 9,
    speedScore: 9,
    noiseScore: 4,
    notes: 'Best independent WordPress news source',
  },
  {
    name: 'Post Status',
    category: 'WordPress',
    type: 'rss',
    homepageUrl: 'https://poststatus.com',
    feedUrl: 'https://poststatus.com/feed/',
    enabled: true,
    trustScore: 9,
    speedScore: 6,
    noiseScore: 2,
    notes: 'WordPress business/community insider',
  },
  {
    name: 'ManageWP Research',
    category: 'WordPress',
    type: 'rss',
    homepageUrl: 'https://managewp.com/blog',
    feedUrl: 'https://managewp.com/blog/feed/',
    enabled: true,
    trustScore: 7,
    speedScore: 5,
    noiseScore: 3,
  },
  {
    name: 'Yoast SEO Blog',
    category: 'WordPress',
    type: 'rss',
    homepageUrl: 'https://yoast.com/seo-blog/',
    feedUrl: 'https://yoast.com/feed/',
    enabled: true,
    trustScore: 8,
    speedScore: 5,
    noiseScore: 3,
  },

  // ── Publishing ─────────────────────────────────────────────────────────────
  {
    name: 'Nieman Lab',
    category: 'Publishing',
    type: 'rss',
    homepageUrl: 'https://www.niemanlab.org',
    feedUrl: 'https://www.niemanlab.org/feed/',
    enabled: true,
    trustScore: 9,
    speedScore: 6,
    noiseScore: 2,
    notes: 'Harvard journalism lab — media/publishing trends',
  },
  {
    name: 'Digiday',
    category: 'Publishing',
    type: 'rss',
    homepageUrl: 'https://digiday.com',
    feedUrl: 'https://digiday.com/feed/',
    enabled: true,
    trustScore: 8,
    speedScore: 7,
    noiseScore: 4,
    notes: 'Media business, ad tech, publisher revenue',
  },
  {
    name: 'Press Gazette',
    category: 'Publishing',
    type: 'rss',
    homepageUrl: 'https://pressgazette.co.uk',
    feedUrl: 'https://pressgazette.co.uk/feed/',
    enabled: true,
    trustScore: 8,
    speedScore: 7,
    noiseScore: 3,
  },
  {
    name: 'WAN-IFRA',
    category: 'Publishing',
    type: 'rss',
    homepageUrl: 'https://wan-ifra.org',
    feedUrl: 'https://wan-ifra.org/feed/',
    enabled: true,
    trustScore: 8,
    speedScore: 5,
    noiseScore: 3,
  },

  // ── Creator Economy ────────────────────────────────────────────────────────
  {
    name: 'The Information – Creator Economy',
    category: 'Creator Economy',
    type: 'rss',
    homepageUrl: 'https://www.theinformation.com',
    feedUrl: 'https://www.theinformation.com/rss',
    enabled: true,
    trustScore: 9,
    speedScore: 6,
    noiseScore: 2,
    notes: 'Paywalled but RSS teaser is useful signal',
  },
  {
    name: 'Axios Media Trends',
    category: 'Creator Economy',
    type: 'rss',
    homepageUrl: 'https://www.axios.com/media',
    feedUrl: 'https://api.axios.com/feed/media',
    enabled: true,
    trustScore: 8,
    speedScore: 8,
    noiseScore: 3,
  },
  {
    name: 'Creator Economy Newsletter (Tory)',
    category: 'Creator Economy',
    type: 'rss',
    homepageUrl: 'https://creatoreconomy.so',
    feedUrl: 'https://creatoreconomy.so/rss',
    enabled: true,
    trustScore: 7,
    speedScore: 3,
    noiseScore: 2,
  },
  {
    name: 'Substack Blog',
    category: 'Creator Economy',
    type: 'rss',
    homepageUrl: 'https://substack.com/blog',
    feedUrl: 'https://substack.com/feed/podcast/1/rss',
    enabled: true,
    trustScore: 7,
    speedScore: 5,
    noiseScore: 3,
  },
  {
    name: 'SparkLoop Blog',
    category: 'Creator Economy',
    type: 'rss',
    homepageUrl: 'https://sparkloop.app/blog',
    feedUrl: 'https://sparkloop.app/blog/rss.xml',
    enabled: true,
    trustScore: 7,
    speedScore: 4,
    noiseScore: 2,
    notes: 'Newsletter monetisation, referrals',
  },
  {
    name: 'Ghost Blog',
    category: 'Creator Economy',
    type: 'rss',
    homepageUrl: 'https://ghost.org/blog',
    feedUrl: 'https://ghost.org/blog/rss/',
    enabled: true,
    trustScore: 7,
    speedScore: 5,
    noiseScore: 2,
  },

  // ── Big Tech ───────────────────────────────────────────────────────────────
  {
    name: 'Google Blog',
    category: 'Big Tech',
    type: 'rss',
    homepageUrl: 'https://blog.google',
    feedUrl: 'https://blog.google/rss/',
    enabled: true,
    trustScore: 10,
    speedScore: 7,
    noiseScore: 3,
    notes: 'Official Google product announcements',
  },
  {
    name: 'Meta Newsroom',
    category: 'Big Tech',
    type: 'rss',
    homepageUrl: 'https://about.fb.com/news',
    feedUrl: 'https://about.fb.com/news/feed/',
    enabled: true,
    trustScore: 9,
    speedScore: 7,
    noiseScore: 3,
  },
  {
    name: 'Microsoft Blog',
    category: 'Big Tech',
    type: 'rss',
    homepageUrl: 'https://blogs.microsoft.com',
    feedUrl: 'https://blogs.microsoft.com/feed/',
    enabled: true,
    trustScore: 9,
    speedScore: 7,
    noiseScore: 4,
  },
  {
    name: 'OpenAI Blog',
    category: 'Big Tech',
    type: 'rss',
    homepageUrl: 'https://openai.com/blog',
    feedUrl: 'https://openai.com/blog/rss.xml',
    enabled: true,
    trustScore: 10,
    speedScore: 8,
    noiseScore: 2,
    notes: 'GPT/AI product launches',
  },
  {
    name: 'Anthropic News',
    category: 'Big Tech',
    type: 'rss',
    homepageUrl: 'https://www.anthropic.com/news',
    feedUrl: 'https://www.anthropic.com/news.rss',
    enabled: true,
    trustScore: 10,
    speedScore: 7,
    noiseScore: 1,
  },
  {
    name: 'Apple Newsroom',
    category: 'Big Tech',
    type: 'rss',
    homepageUrl: 'https://www.apple.com/newsroom',
    feedUrl: 'https://www.apple.com/newsroom/rss-feed.rss',
    enabled: true,
    trustScore: 10,
    speedScore: 8,
    noiseScore: 2,
  },

  // ── Tools ──────────────────────────────────────────────────────────────────
  {
    name: 'Product Hunt',
    category: 'Tools',
    type: 'rss',
    homepageUrl: 'https://www.producthunt.com',
    feedUrl: 'https://www.producthunt.com/feed',
    enabled: true,
    trustScore: 6,
    speedScore: 10,
    noiseScore: 8,
    notes: 'Very noisy, but first to surface new tools',
  },
  {
    name: 'Hacker News',
    category: 'Tools',
    type: 'rss',
    homepageUrl: 'https://news.ycombinator.com',
    feedUrl: 'https://news.ycombinator.com/rss',
    enabled: true,
    trustScore: 7,
    speedScore: 9,
    noiseScore: 7,
    notes: 'High noise, but catches emerging dev tools fast',
  },
  {
    name: 'Zapier Blog',
    category: 'Tools',
    type: 'rss',
    homepageUrl: 'https://zapier.com/blog',
    feedUrl: 'https://zapier.com/blog/feeds/latest/',
    enabled: true,
    trustScore: 7,
    speedScore: 5,
    noiseScore: 4,
  },
  {
    name: 'Make (formerly Integromat) Blog',
    category: 'Tools',
    type: 'rss',
    homepageUrl: 'https://www.make.com/en/blog',
    feedUrl: 'https://www.make.com/en/blog/feed',
    enabled: true,
    trustScore: 6,
    speedScore: 5,
    noiseScore: 4,
  },
  {
    name: 'Buffer Blog',
    category: 'Tools',
    type: 'rss',
    homepageUrl: 'https://buffer.com/resources',
    feedUrl: 'https://buffer.com/resources/rss/',
    enabled: true,
    trustScore: 7,
    speedScore: 5,
    noiseScore: 3,
  },
  {
    name: 'Notion Blog',
    category: 'Tools',
    type: 'rss',
    homepageUrl: 'https://www.notion.so/blog',
    feedUrl: 'https://www.notion.so/blog/rss.xml',
    enabled: true,
    trustScore: 7,
    speedScore: 5,
    noiseScore: 3,
  },
  {
    name: 'Figma Blog',
    category: 'Tools',
    type: 'rss',
    homepageUrl: 'https://www.figma.com/blog',
    feedUrl: 'https://www.figma.com/blog/feed/',
    enabled: true,
    trustScore: 7,
    speedScore: 6,
    noiseScore: 2,
  },
  {
    name: 'Vercel Blog',
    category: 'Tools',
    type: 'rss',
    homepageUrl: 'https://vercel.com/blog',
    feedUrl: 'https://vercel.com/feed.xml',
    enabled: true,
    trustScore: 8,
    speedScore: 7,
    noiseScore: 2,
    notes: 'Relevant for Next.js/deployment ecosystem',
  },

  // ── Additional AI/ML Sources ───────────────────────────────────────────────
  {
    name: 'Google DeepMind Blog',
    category: 'AI',
    type: 'rss',
    homepageUrl: 'https://deepmind.google/discover/blog',
    feedUrl: 'https://deepmind.google/blog/rss.xml',
    enabled: true,
    trustScore: 10,
    speedScore: 5,
    noiseScore: 1,
    notes: 'Research breakthroughs, low volume',
  },
  {
    name: 'Hugging Face Blog',
    category: 'AI',
    type: 'rss',
    homepageUrl: 'https://huggingface.co/blog',
    feedUrl: 'https://huggingface.co/blog/feed.xml',
    enabled: true,
    trustScore: 9,
    speedScore: 7,
    noiseScore: 3,
    notes: 'ML models, datasets, open source AI',
  },
  {
    name: 'Wired – AI',
    category: 'AI',
    type: 'rss',
    homepageUrl: 'https://www.wired.com/tag/artificial-intelligence/',
    feedUrl: 'https://www.wired.com/feed/tag/artificial-intelligence/latest/rss',
    enabled: true,
    trustScore: 7,
    speedScore: 6,
    noiseScore: 5,
  },

  // ── Additional SEO/Content ─────────────────────────────────────────────────
  {
    name: 'Backlinko',
    category: 'SEO',
    type: 'rss',
    homepageUrl: 'https://backlinko.com/blog',
    feedUrl: 'https://backlinko.com/blog/feed',
    enabled: true,
    trustScore: 8,
    speedScore: 3,
    noiseScore: 1,
    notes: 'Brian Dean — low volume, high quality SEO research',
  },
  {
    name: 'Content Marketing Institute',
    category: 'Publishing',
    type: 'rss',
    homepageUrl: 'https://contentmarketinginstitute.com',
    feedUrl: 'https://feeds.feedblitz.com/cmi/all',
    enabled: true,
    trustScore: 7,
    speedScore: 4,
    noiseScore: 4,
  },
  {
    name: 'Copyblogger',
    category: 'Publishing',
    type: 'rss',
    homepageUrl: 'https://copyblogger.com',
    feedUrl: 'https://copyblogger.com/feed/',
    enabled: true,
    trustScore: 7,
    speedScore: 3,
    noiseScore: 3,
  },
];

// Total: 55 sources across 9 categories
